#!/bin/bash

FILES=$(git diff --cached --name-only --diff-filter=d "*.js" | sed 's/ /\\ /g' | awk '!/^public\// {print $0}' | awk '!/^src\/modernizr.js/ {print $0}')

if [ -z "$FILES" ]; then
    exit 0
fi

echo "$FILES" | xargs npx eslint

if [ $? -ne 0 ]; then
    exit 1
fi