export const TOGGLE_DARK = 'TOGGLE_DARK'
export const SET_DECK_INDEX = 'SET_DECK_INDEX'
export const SET_DECKS = 'SET_DECKS'
export const ADD_CARD = 'ADD_CARD'
export const SET_CARD = 'SET_CARD'
export const DELETE_CARD = 'DELETE_CARD'
export const SET_BUCKETS = 'SET_BUCKETS'
